{% set name = "benchpots" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 0b498acff9a63e03f78a3a066909a94023abe32a428bb45ec9b698c6a35d448b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - h5py
    - scipy
    - numpy
    - pandas
    - pyarrow
    - scikit-learn
    - pytorch >=1.10.0
    - tsdb >=0.6.1
    - pygrinder >=0.6.2

test:
  imports:
    - benchpots

about:
  home: https://github.com/WenjieDu/BenchPOTS
  summary: 'A Python Toolbox for Benchmarking Machine Learning on Partially-Observed Time Series'
  description: |
    To evaluate the performance of algorithms on POTS datasets, a benchmarking toolkit is necessary, hence the ecosystem library BenchPOTS is developed.
    BenchPOTS provides the standard and unified preprocessing pipelines of a variety of POTS datasets.
    It supports a variety of evaluation tasks to help users understand the performance of different algorithms.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.pypots.com
  dev_url: https://github.com/WenjieDu/BenchPOTS

extra:
  recipe-maintainers:
    - WenjieDu
