{% set name = "benchpots" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 12726b7db046ba0f3ca04a4be8b3a3075608e55fb666a85791d97d91d59a43d6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - h5py
    - numpy
    - pandas
    - pyarrow
    - scikit-learn
    - pytorch >=1.10.0
    - tsdb >=0.4
    - pygrinder >=0.6

test:
  imports:
    - benchpots
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/WenjieDu/BenchPOTS
  summary: 'A Python Toolbox for Benchmarking Machine Learning on Partially-Observed Time Series'
  description: |
    To evaluate the performance of algorithms on POTS datasets, a benchmarking toolkit is necessary, hence the ecosystem library BenchPOTS is developed.
    BenchPOTS provides the standard and unified preprocessing pipelines of a variety of POTS datasets.
    It supports a variety of evaluation tasks to help users understand the performance of different algorithms.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://docs.pypots.com
  dev_url: https://github.com/WenjieDu/BenchPOTS

extra:
  recipe-maintainers:
    - WenjieDu
